name: mlflow-environment
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - scikit-learn
  - pip
  - pandas
  - numpy
  - openjdk
  - pip:
    - pyspark
    - mlflow
    - azureml-mlflow
    - azureml-defaults
